// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp78eKXWRt74vW1mDDNdePH5hvSIIoQs4',
    appId: '1:231855868930:web:165653951d7f13e17b2b1b',
    messagingSenderId: '231855868930',
    projectId: 'easyshoping-c782c',
    authDomain: 'easyshoping-c782c.firebaseapp.com',
    storageBucket: 'easyshoping-c782c.appspot.com',
    measurementId: 'G-CH7EJPNNFE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI2gpo77Tt7Z8snDXWv-B3Q7GPuKdfgfM',
    appId: '1:231855868930:ios:811d92a8b39c6d277b2b1b',
    messagingSenderId: '231855868930',
    projectId: 'easyshoping-c782c',
    storageBucket: 'easyshoping-c782c.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI2gpo77Tt7Z8snDXWv-B3Q7GPuKdfgfM',
    appId: '1:231855868930:ios:811d92a8b39c6d277b2b1b',
    messagingSenderId: '231855868930',
    projectId: 'easyshoping-c782c',
    storageBucket: 'easyshoping-c782c.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp78eKXWRt74vW1mDDNdePH5hvSIIoQs4',
    appId: '1:231855868930:web:77a784e796ba39f17b2b1b',
    messagingSenderId: '231855868930',
    projectId: 'easyshoping-c782c',
    authDomain: 'easyshoping-c782c.firebaseapp.com',
    storageBucket: 'easyshoping-c782c.appspot.com',
    measurementId: 'G-1XEVF5XESH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4GQGGvaHSuSHejal3dyTVkj083Z5gsOQ',
    appId: '1:231855868930:android:03dc2f0a71e7c95c7b2b1b',
    messagingSenderId: '231855868930',
    projectId: 'easyshoping-c782c',
    storageBucket: 'easyshoping-c782c.appspot.com',
  );

}